import type { RouteRecordRaw } from 'vue-router'

import { MANAGER_PERMISSION } from '@/shared/constants/permissions'

const AdminLayout = () => import('@/app/layouts/AdminLayout.vue')
const LoginView = () => import('@/modules/auth/views/LoginView.vue')
const DashboardView = () => import('@/modules/dashboard/views/DashboardView.vue')
const UsersListView = () => import('@/modules/users/views/UsersListView.vue')
const UsersPermissionsView = () => import('@/modules/users/views/UsersPermissionsView.vue')
const NoticesListView = () => import('@/modules/notices/views/NoticesListView.vue')
const NoticeEditorView = () => import('@/modules/notices/views/NoticeEditorView.vue')
const SchoolListView = () => import('@/modules/school-club-student/views/SchoolListView.vue')
const ClubListView = () => import('@/modules/school-club-student/views/ClubListView.vue')
const StudentListView = () => import('@/modules/school-club-student/views/StudentListView.vue')
const ForbiddenView = () => import('@/modules/system/views/ForbiddenView.vue')
const WorksListView = () => import('@/modules/works/views/WorksListView.vue')
const WorkReviewsView = () => import('@/modules/works/views/WorkReviewsView.vue')
const WorkDetailView = () => import('@/modules/works/views/WorkDetailView.vue')
const ClaimsListView = () => import('@/modules/works/views/ClaimsListView.vue')
const ComplaintsListView = () => import('@/modules/works/views/ComplaintsListView.vue')
const CommentComplaintsView = () => import('@/modules/works/views/CommentComplaintsView.vue')
const OperationLogView = () => import('@/modules/works/views/OperationLogView.vue')
const MessagesListView = () => import('@/modules/messages/views/MessagesListView.vue')
const FeedbackManageListView = () => import('@/modules/feedback/views/FeedbackManageListView.vue')
const BackgroundsListView = () => import('@/modules/backgrounds/views/BackgroundsListView.vue')

export const adminChildren: RouteRecordRaw[] = [
  {
    path: 'dashboard',
    name: 'dashboard',
    component: DashboardView,
    meta: {
      title: '控制台',
      subtitle: '把当前账号、模块入口与阶段重点集中在一个轻量首页。',
      requiresAuth: true,
      requiresManager: true,
      menuLabel: '仪表盘',
      menuGroup: 'dashboard',
      menuGroupLabel: '概览',
      groupOrder: 10,
      menuOrder: 10,
    },
  },
  {
    path: 'users/list',
    name: 'users-list',
    component: UsersListView,
    meta: {
      title: '用户列表',
      subtitle: '查看用户分页结果，并保留新建用户的入口。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermission: MANAGER_PERMISSION.THI_MAINTAINER,
      menuLabel: '用户列表',
      menuGroup: 'users',
      menuGroupLabel: '用户',
      groupOrder: 20,
      menuOrder: 10,
    },
  },
  {
    path: 'users/permissions',
    name: 'users-permissions',
    component: UsersPermissionsView,
    meta: {
      title: '权限调整',
      subtitle: '按真实权限选项管理账号角色，不再沿用 V1 的组合勾选误导。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermission: MANAGER_PERMISSION.THI_MAINTAINER,
      menuLabel: '权限调整',
      menuGroup: 'users',
      menuGroupLabel: '用户',
      groupOrder: 20,
      menuOrder: 20,
    },
  },
  {
    path: 'users/complaints',
    name: 'users-complaints',
    component: FeedbackManageListView,
    meta: {
      title: '用户投诉',
      subtitle: '处理针对用户的投诉反馈，仅更新反馈状态和处理备注。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.THI_MAINTAINER,
      menuLabel: '用户投诉',
      menuGroup: 'users',
      menuGroupLabel: '用户',
      groupOrder: 20,
      menuOrder: 30,
      feedbackType: 'USER',
    },
  },
  {
    path: 'notices',
    name: 'notices-list',
    component: NoticesListView,
    meta: {
      title: '公告列表',
      subtitle: '延续 V1 的列表、新增、编辑节奏，但把交互收束到统一壳层。',
      requiresAuth: true,
      requiresManager: true,
      menuLabel: '公告列表',
      menuGroup: 'notices',
      menuGroupLabel: '公告',
      groupOrder: 30,
      menuOrder: 10,
    },
  },
  {
    path: 'notices/new',
    name: 'notices-new',
    component: NoticeEditorView,
    meta: {
      title: '发布公告',
      subtitle: '面向管理员的新公告编辑器。',
      requiresAuth: true,
      requiresManager: true,
      hiddenInMenu: true,
    },
  },
  {
    path: 'notices/:noticeId/edit',
    name: 'notices-edit',
    component: NoticeEditorView,
    meta: {
      title: '编辑公告',
      subtitle: '支持作者本人或更高权限管理员修改公告。',
      requiresAuth: true,
      requiresManager: true,
      hiddenInMenu: true,
    },
  },
  {
    path: 'schools',
    name: 'schools-list',
    component: SchoolListView,
    meta: {
      title: '学园列表',
      subtitle: '管理所有学园及其下属的部团与学生。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermission: 16,
      menuLabel: '学园、部团、学生',
      menuGroup: 'system',
      menuGroupLabel: '系统',
      groupOrder: 60,
      menuOrder: 50,
    },
  },
  {
    path: 'schools/:schoolId/clubs',
    name: 'clubs-list',
    component: ClubListView,
    meta: {
      title: '部团列表',
      subtitle: '管理该学园下的所有部团。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermission: 16,
      hiddenInMenu: true,
    },
  },
  {
    path: 'schools/:schoolId/clubs/:clubId/students',
    name: 'students-list',
    component: StudentListView,
    meta: {
      title: '学生列表',
      subtitle: '管理该部团下的所有学生。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermission: 16,
      hiddenInMenu: true,
    },
  },
  {
    path: 'works/reviews',
    name: 'works-reviews',
    component: WorkReviewsView,
    meta: {
      title: '上传审核',
      subtitle: '审核新上传和修改后的作品；处理结果静默记录，不发送电子邮件。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.SEC_MAINTAINER,
      menuLabel: '上传审核',
      menuGroup: 'works',
      menuGroupLabel: '作品管理',
      groupOrder: 40,
      menuOrder: 5,
    },
  },
  {
    path: 'works/list',
    name: 'works-list',
    component: WorksListView,
    meta: {
      title: '作品管理',
      subtitle: '管理全部作品，支持封禁、下架、删除、恢复和内容修改。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.SEC_MAINTAINER,
      menuLabel: '作品管理',
      menuGroup: 'works',
      menuGroupLabel: '作品管理',
      groupOrder: 40,
      menuOrder: 10,
    },
  },
  {
    path: 'works/:workId/detail',
    name: 'works-detail',
    component: WorkDetailView,
    meta: {
      title: '作品详情',
      subtitle: '查看作品详情，可执行封禁/下架/删除/恢复操作。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.SEC_MAINTAINER,
      hiddenInMenu: true,
    },
  },
  {
    path: 'works/claims',
    name: 'works-claims',
    component: ClaimsListView,
    meta: {
      title: '认领管理',
      subtitle: '审批认领申请、撤销认领、指派作者。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.SEC_MAINTAINER,
      menuLabel: '认领管理',
      menuGroup: 'works',
      menuGroupLabel: '作品管理',
      groupOrder: 40,
      menuOrder: 20,
    },
  },
  {
    path: 'works/complaints',
    name: 'works-complaints',
    component: ComplaintsListView,
    meta: {
      title: '投诉处理',
      subtitle: '查看和处理作品投诉，处理时可联动封禁/下架/删除。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.SEC_MAINTAINER,
      menuLabel: '投诉处理',
      menuGroup: 'works',
      menuGroupLabel: '作品管理',
      groupOrder: 40,
      menuOrder: 30,
    },
  },
  {
    path: 'works/comment-complaints',
    name: 'works-comment-complaints',
    component: CommentComplaintsView,
    meta: {
      title: '评论投诉',
      subtitle: '查看和处理用户对评论内容的投诉举报。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.FIR_MAINTAINER,
      menuLabel: '评论投诉',
      menuGroup: 'works',
      menuGroupLabel: '作品管理',
      groupOrder: 40,
      menuOrder: 35,
    },
  },
  {
    path: 'works/logs',
    name: 'works-logs',
    component: OperationLogView,
    meta: {
      title: '操作日志',
      subtitle: '查看所有作品管理操作的审计日志。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.SEC_MAINTAINER,
      menuLabel: '操作日志',
      menuGroup: 'works',
      menuGroupLabel: '作品管理',
      groupOrder: 40,
      menuOrder: 40,
    },
  },
  {
    path: 'messages/list',
    name: 'messages-list',
    component: MessagesListView,
    meta: {
      title: '留言管理',
      subtitle: '查看、搜索、编辑和删除用户留言板内容。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.FIR_MAINTAINER,
      menuLabel: '留言管理',
      menuGroup: 'messages',
      menuGroupLabel: '留言管理',
      groupOrder: 50,
      menuOrder: 10,
    },
  },
  {
    path: 'system/feedback-bug',
    name: 'system-feedback-bug',
    component: FeedbackManageListView,
    meta: {
      title: 'BUG反馈',
      subtitle: '集中查看用户提交的 BUG 反馈，并更新处理状态。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.ADMINISTRATOR,
      menuLabel: 'BUG反馈',
      menuGroup: 'system',
      menuGroupLabel: '系统',
      groupOrder: 60,
      menuOrder: 60,
      feedbackType: 'BUG',
    },
  },
  {
    path: 'system/feedback-suggestion',
    name: 'system-feedback-suggestion',
    component: FeedbackManageListView,
    meta: {
      title: '意见反馈',
      subtitle: '集中查看用户建议，并回写处理状态和备注。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.ADMINISTRATOR,
      menuLabel: '意见反馈',
      menuGroup: 'system',
      menuGroupLabel: '系统',
      groupOrder: 60,
      menuOrder: 70,
      feedbackType: 'SUGGESTION',
    },
  },
  {
    path: 'system/feedback-other',
    name: 'system-feedback-other',
    component: FeedbackManageListView,
    meta: {
      title: '其他反馈',
      subtitle: '处理未归类的其他反馈，仅做状态与备注更新。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.ADMINISTRATOR,
      menuLabel: '其他反馈',
      menuGroup: 'system',
      menuGroupLabel: '系统',
      groupOrder: 60,
      menuOrder: 80,
      feedbackType: 'OTHER',
    },
  },
  {
    path: 'system/backgrounds',
    name: 'system-backgrounds',
    component: BackgroundsListView,
    meta: {
      title: '背景图设置',
      subtitle: '管理各页面展示的背景图，支持多图、排序与启用。',
      requiresAuth: true,
      requiresManager: true,
      minManagerPermissionBit: MANAGER_PERMISSION.ADVANCED_ADMINISTRATOR,
      menuLabel: '背景图设置',
      menuGroup: 'sysmanage',
      menuGroupLabel: '系统管理',
      groupOrder: 70,
      menuOrder: 10,
    },
  },
  {
    path: '403',
    name: 'forbidden',
    component: ForbiddenView,
    meta: {
      title: '无权限',
      subtitle: '当前账号已登录，但缺少访问这个模块的能力。',
      requiresAuth: true,
      requiresManager: true,
      hiddenInMenu: true,
    },
  },
]

export const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'login',
    component: LoginView,
    meta: {
      title: '登录',
      subtitle: '仅 MANAGER 身份可进入 BARC 管理后台。',
      hiddenInMenu: true,
    },
  },
  {
    path: '/',
    component: AdminLayout,
    children: [
      {
        path: '',
        redirect: { name: 'dashboard' },
      },
      ...adminChildren,
    ],
  },
  {
    path: '/:pathMatch(.*)*',
    redirect: { name: 'dashboard' },
  },
]
